name: learning-appearance-bias
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.6
  - pip
  - pip:
    - enlighten==1.1.0
    - face_recognition==1.2.3
    - imagenetscraper
    - tensorflow-hub==0.1.1
    - tensorflow
    - tensorboard==1.12.0
    - numpy>=1.15.4
    - keras
    - pandas
    - scikit-learn
    - grequests
    - matplotlib
    - seaborn
    - ImageScraper
    - Pillow

